### ISSUE TITLE
Fix bad practice of http instead of // in links to images and scripts

### ISSUE THREAD

**Issue by SenchoPoro42** [Leantime/leantime#169]
I have a correctly used ssl certificate, but because the webpage is hardcoded with http, I can't have any images without allowing mixed content which is incredibly unsafe.

Please replace http:// with just // with at least the following that I found:
http://domain.com/css/style.default.css?v=2.0.14 on line 19
http://domain.com/css/style.custom.php?color=1b75bb&v=2.0.14 on line 20
http://domain.com/css/main.css on line 21
http://domain.com/js/libs/jquery-1.9.1.min.js on line 24
http://domain.com/js/libs/jquery-migrate-1.1.1.min.js on line 25
http://domain.com/js/libs/jquery-ui-1.9.2.min.js on line 26
http://domain.com/js/libs/modernizr.min.js on line 27
http://domain.com/js/libs/bootstrap.min.js on line 28
http://domain.com/js/libs/jquery.cookie.js on line 29
http://domain.com/images/logo.png on line 63

**Comment by marcelfolaron** [comment]
Thanks for reaching out. Which version are you using? These issues had been resolved as of 2.0.12.

If you open the website via https:// all calls afterwards should be https:// as well. You can also force using https by setting `$appURL` in the `configuration.php`

**Comment by SenchoPoro42** [comment]
I see and that’s great! I should probably have posted on docket, but couldn’t figure it out. I installed the latest docker today.

Kind regards,
Philip Kartin

On 19 Mar 2020, at 15.53, Marcel Folaron <notifications@github.com> wrote:

﻿

Thanks for reaching out. Which version are you using? These issues had been resolved as of 2.0.12.

If you open the website via https:// all calls afterwards should be https:// as well. You can also force using https by setting $appURL in the configuration.php

**Comment by marcelfolaron** [comment]
There is a bug open on the docker repo to allow setting the appURL as paramter. https://github.com/Leantime/docker-leantime/issues/8 Closing this one

**Comment by cstrachan88** [comment]
I am still having this issue for only the logo.png after following your suggestion of setting "https" in the appURL parameter. See also #231. I just put in a pull request with a fix #301. Somehow, the `$_SESSION["companysettings.logoPath"]` variable is being set with http regardless of the appURL parameter.
