### ISSUE TITLE
[BUG] Updating from 3.1.4 to the latest version makes Leantime unusable as login does not work anymore 

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [Leantime/leantime#2649]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
After updating to the latest version, Leantime updates the database upon first login. After that, I can't login to Leantime any more. No error message, the credentials just won't work. I had to manually revert back to 3.1.4 and restore my database backup to use Leantime again.
  
**To Reproduce**
Use a 3.1.4 self-hosted installation and update to the latest version.

**Expected behavior**
Being able to login after Leantime has updated the database.

**Leantime Version**
reverted back to 3.1.4, wanted to use the latest version

**PHP / MySQL Version**
PHP 8.1.9 / MySQL 9.0.1

**Comment by mattjbayly** [comment]
I am also getting the same error:

`
[2024-09-08 19:21:05] production.CRITICAL: PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'zp_calendar' already exists in /var/www/html/leantime/app/Domain/Install/Repositories/Install.php:239
Stack trace:
#0 /var/www/html/leantime/app/Domain/Install/Repositories/Install.php(239): PDOStatement->execute()
#1 /var/www/html/leantime/app/Domain/Install/Controllers/Index.php(95): Leantime\Domain\Install\Repositories\Install->setupDB()
#2 /var/www/html/leantime/app/Core/Controller/Controller.php(94): Leantime\Domain\Install\Controllers\Index->post()
#3 /var/www/html/leantime/app/Core/Controller/Controller.php(53): Leantime\Core\Controller\Controller->executeActions()
#4 [internal function]: Leantime\Core\Controller\Controller->__construct()
#5 /var/www/html/leantime/vendor/illuminate/container/Container.php(952): ReflectionClass->newInstanceArgs()
#6 /var/www/html/leantime/vendor/illuminate/container/Container.php(795): Illuminate\Container\Container->build()
#7 /var/www/html/leantime/app/Core/Bootstrap/Application.php(501): Illuminate\Container\Container->resolve()
#8 /var/www/html/leantime/vendor/illuminate/container/Container.php(731): Leantime\Core\Bootstrap\Application->resolve()
#9 /var/www/html/leantime/app/Core/Bootstrap/Application.php(486): Illuminate\Container\Container->make()
#10 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(133): Leantime\Core\Bootstrap\Application->make()
#11 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(78): Leantime\Core\Controller\Frontcontroller::executeAction()
#12 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(84): Leantime\Core\Controller\Frontcontroller::dispatch()
#13 /var/www/html/leantime/app/Core/Http/HttpKernel.php(69): Leantime\Core\Controller\Frontcontroller::dispatch_request()
#14 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(144): Leantime\Core\Http\HttpKernel->Leantime\Core\Http\{closure}()
#15 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/leantime/app/Core/Http/HttpKernel.php(69): Illuminate\Pipeline\Pipeline->then()
#17 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(144): Leantime\Core\Http\HttpKernel->Leantime\Core\Http\{closure}()
#18 /var/www/html/leantime/app/Core/Middleware/CurrentProject.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\CurrentProject->handle()
#20 /var/www/html/leantime/app/Core/Middleware/Localization.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\Localization->handle()
#22 /var/www/html/leantime/app/Core/Middleware/Auth.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\Auth->handle()
#24 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(113): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\RequestRateLimiter->handle()
#26 /var/www/html/leantime/app/Core/Middleware/Updated.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\Updated->handle()
#28 /var/www/html/leantime/app/Core/Middleware/Installed.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\Installed->handle()
#30 /var/www/html/leantime/app/Core/Middleware/StartSession.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/leantime/app/Core/Middleware/StartSession.php(89): Leantime\Core\Middleware\StartSession->handleStatefulRequest()
#32 /var/www/html/leantime/app/Core/Middleware/StartSession.php(66): Leantime\Core\Middleware\StartSession->handleRequestWhileBlocking()
#33 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\StartSession->handle()
#34 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\InitialHeaders->handle()
#36 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(183): Leantime\Core\Middleware\TrustProxies->handle()
#38 /var/www/html/leantime/vendor/illuminate/pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/leantime/app/Core/Http/HttpKernel.php(60): Illuminate\Pipeline\Pipeline->then()
#40 /var/www/html/leantime/app/Core/Bootstrap/Bootloader.php(152): Leantime\Core\Http\HttpKernel->handle()
#41 /var/www/html/leantime/app/Core/Bootstrap/Bootloader.php(129): Leantime\Core\Bootstrap\Bootloader->handleRequest()
#42 /var/www/html/leantime/public/index.php(13): Leantime\Core\Bootstrap\Bootloader->boot()
`

**Comment by danmb315** [comment]
i have the same problem, do you found a solution?

**Comment by marcelfolaron** [comment]
Do you have any other error messages from the logs?

**Comment by schories** [comment]
Also 3.2.1 is affected again. I am using the official [docker image](https://hub.docker.com/layers/leantime/leantime/3.2.1/images/sha256-67c3d5dd022f2c78faf7a931cd433707b374c58ac07a7e43313f248f18c5beac?context=explore).

![Screenshot 2024-09-23 100640](https://github.com/user-attachments/assets/e534af5c-9005-4561-9db1-ce9a07c9b0de)

**Comment by schories** [comment]
Here is a fix which worked for me, means in case you have (e.g. the commercial) plugins installed:

1. stop leantime (docker)
2. move all the subdirs from /plugins to safe backup place; /plugins dir must be empty
3. start leantime (docker), login should work fine again; however, additional steps 4-6 are still required
4. redownload ALL apps from "app marketplace / explore apps" (re-)using your license key for each app
5. disable ALL apps under "app marketplace / my apps"
6. enable ALL apps under "app marketplace / my apps" again

A bit alarming (receiving a generic "error 500" message even on the login screen) and a bit tedious (fiddling with individual license keys and plugins/apps again) - but overall fixed in under 10 minutes.

I hope you find this information helpful and it saves you time.

**Comment by marcelfolaron** [comment]
Thank you for the write up. 
The update from 3.1.4 to 3.2 requires all plugins to be disabled before the update. https://github.com/Leantime/leantime/releases/tag/v3.2.0

I'll see if we can check plugin versions early in the stack to not cause a 500 but some plugins tie in pretty early in the call stack.

**Comment by schories** [comment]
@marcelfolaron Thank you, Marcel. Personally I can live with that information & behavior, there are probably other more important topics.

**Comment by RKLBusinessDevelopment** [comment]
This doesn't fix the initial problem I have reported. I have not used any plugins at all and made sure there are none active when performing the upgrade to the latest Leantime version.

**Comment by schories** [comment]
@RKLBusinessDevelopment Sorry to hear that. Can you please enable [debug ](https://github.com/Leantime/leantime/blob/master/config/configuration.sample.php#L27) and please let us know, of the detailed error information in your case? I assume you run your very own classic installation not based the official docker image, correct?

As for @mattjbayly - sounds like the installer already ran but has not finished the first time. Depending on your server configuration (esp. php running as apache module or via fcgi) it could be something like `max_execution_time` being set to low, so that the scripts which invoke the MySQL statements are limited in some way. Can you please provide the output of [phpinfo](https://www.php.net/manual/en/function.phpinfo.php)? I assume you run your very own classic installation not based the official docker image, correct?

Thank you!

**Comment by schories** [comment]
However, it is strange that [setupDB](https://github.com/Leantime/leantime/blob/master/app/Domain/Install/Repositories/Install.php#L219) is being run, as I would expect to run [updateDB](https://github.com/Leantime/leantime/blob/master/app/Domain/Install/Repositories/Install.php#L259) as all of you seem to update - not to freshly install. 

So somewhat makes 3.2.x believe, that there is no (accessible) leantime database - and it starts an installation into an already existing database, which then fails as of course tables/views already exist.

**Comment by schories** [comment]
These 2 commits introduced with 3.2.0 could be relevant:

https://github.com/Leantime/leantime/commit/d58e1648f3d1fd8a115b6ba712b74000533385aa

https://github.com/Leantime/leantime/commit/85a96484e0017f24f9d82e79f59a29e4b00b9d36

@RKLBusinessDevelopment  @mattjbayly  Possibly there is an issue with the database/schema versioning - or detecting the version correctly. Thus it would be helpful if you please provide the version information as it is currently stored in your leantime MySQL database. Then we can hopefully see what might be the actual issue / root cause.

**Comment by PGostek** [comment]
Exactly same story here, but run on docker on Synolog DSM.  I tried a full fresh installation of 3.20 or 3.2.1, but still behave as described above.

**Comment by kh3b** [comment]
Hi, same here.
I just updated your official docker image on synology to 3.2.1
After that the login is no longer possible. After login the page just refresh and shows the login screen again.

**Comment by marcelfolaron** [comment]
From what I can gather across other issue reports, the main problem is a new config that set cookies to be secure only. Meaning they have to be served via https. 
You can either try use a self signed certificate via reverse proxy or you can set the config in app/core until we have a fix out to make this a config var. Solution is outlined here: https://github.com/Leantime/leantime/issues/2699

**Comment by kh3b** [comment]
Thanks!
Setting the secure flag to false helped!

**Comment by marcelfolaron** [comment]
3.3 now has a config for LEANTIME_SESSION_SECURE which solves this issue
